version: '3.8'
services:
  chroma-db:
    image: chromadb/chroma:latest
    container_name: chroma-db
    ports:
      - '8000:8000'
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma_data:/chroma/.chroma/index
      - ./data/documents:/app/data/documents
volumes:
  chroma_data:
